version: '3.8'

services:
  api:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - huggingface_cache:/app/.cache/huggingface
    restart: unless-stopped
    environment:
      - HF_HOME=/app/.cache/huggingface

volumes:
  huggingface_cache: 